add splitter

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,34 +1,50 @@
-repo='hantbk/vtsbackup'
-version=`get_latest_release`
+#!/usr/bin/env sh
+
+set -u
+
+type curl > /dev/null || { echo "curl: not found"; exit 1; }
+
+set -e
 
 get_latest_release() {
- 	curl --silent "https://api.github.com/repos/$repo/releases/latest" | # Get latest release from GitHub api
- 		grep '"tag_name":' |                                            # Get tag line
- 		sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
+  local repo="$1"
+	curl -sSL "https://api.github.com/repos/${repo}/releases/latest" | \
+    awk 'BEGIN{FS=": |,|\""}; /tag_name/{print $5}'
 }
 
+repo="hantbk/vtsbackup"
+version="$(get_latest_release "${repo}")"  # v1.2.0
+platform="$(uname | tr "[A-Z]" "[a-z]")"  # Linux => linux
+arch="$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/')"  # x86_64 => amd64, aarch64 => arm64
 
-if [[ `uname` == 'Darwin' ]]; then
-   platform='darwin'
-else
-   platform='linux'
+package="vtsbackup-${platform}-${arch}.tar.gz"
+package_url="https://github.com/${repo}/releases/download/${version}/${package}"
+bin="vtsbackup"
+dest_dir="/usr/local/bin"
+bin_path="${dest_dir}/${bin}"
+tmp_dir="$(mktemp -d)"
+
+trap "rm -r ${tmp_dir}" EXIT
+
+if test -e "${bin_path}"; then
+   current_version="v$("${bin_path}" -v | awk '{print $NF}')"
+   if test "${current_version}" = "${version}"; then
+     echo "${bin} is already updated, no need to upgrade."
+     exit 0
+   else
+     echo "There is a new version of ${bin}, starting to upgrade from ${current_version} to ${version}."
+   fi
 fi
 
-if [[ `arch` == 'arm64' ]]; then
- 	arch='arm64'
+cd "${tmp_dir}"
+curl -sSL "${package_url}" | tar xzf -
+
+if test $(id -u) -eq 0; then
+   mv "${bin}" "${dest_dir}"
 else
- 	arch='amd64'
+   sudo mv "${bin}" "${dest_dir}"
 fi
 
-curl -SLo vtsbackup.tar.gz https://github.com/hantbk/vtsbackup/releases/download/$version/vtsbackup-$platform-$arch.tar.gz
+mkdir -p ~/.vtsbackup
 
-tar zxf vtsbackup.tar.gz
-
-if [[ `whoami` == 'root' ]]; then
-   mv vtsbackup /usr/local/bin/vtsbackup
-else
-   sudo mv vtsbackup /usr/local/bin/vtsbackup
-fi
-
-mkdir -p ~/.vtsbackup && touch ~/.vtsbackup/vtsbackup.yml
-rm vtsbackup.tar.gz
+echo "${bin} ${version} has been installed."
